#!/bin/sh

STAGED_FILES=$(git diff --staged --name-only --diff-filter=ACM)

just format

git diff --exit-code -- $STAGED_FILES || {
  echo "Staged files were reformatted. Please re-stage them and commit again."
  exit 1
}
