name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}

      - uses: cachix/install-nix-action@v31

      - name: Build binary
        run: nix develop --command just prod

      - name: Rename binary
        run: mv niri-outputs-generator niri-outputs-generator-${{ matrix.arch }}

      - uses: actions/upload-artifact@v7
        with:
          name: niri-outputs-generator-${{ matrix.arch }}
          path: niri-outputs-generator-${{ matrix.arch }}
