name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: Delete release and tag
        run: gh release delete latest --cleanup-tag --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: |
          gh release create latest \
            --title "latest" \
            --notes "🙂✌️" \
            ./artifacts/**/*
